import type { FieldConfig } from '../types/config.types'

const STATUS_BADGE_COLORS: Record<string, string> = {
  DELIVERED: 'green',
  SHIPPED: 'blue',
  'OUT FOR DELIVERY': 'cyan',
  CONFIRMED: 'indigo',
  PLACED: 'purple',
  CANCELLED: 'red',
  RETURNED: 'orange',
  PENDING: 'yellow',
  Open: 'blue',
  'Pending Customer': 'yellow',
  'On Hold': 'orange',
  Resolved: 'green',
  Closed: 'gray',
  Active: 'green',
  Inactive: 'gray',
  Suspended: 'red',
  Bronze: 'amber',
  Silver: 'slate',
  Gold: 'yellow',
  Platinum: 'blue',
}

export const FIELDS_CONFIG: Record<string, FieldConfig[]> = {
  'customer.profile': [
    { key: 'customer_id', label: 'Customer ID', type: 'string', sortable: true },
    { key: 'name', label: 'Full Name', type: 'string', sortable: true },
    { key: 'phone', label: 'Phone', type: 'pii', piiType: 'phone' },
    { key: 'email', label: 'Email', type: 'pii', piiType: 'email' },
    { key: 'address', label: 'Address', type: 'pii', piiType: 'address' },
    { key: 'pan', label: 'PAN', type: 'pii', piiType: 'pan', roles: ['nhqFinance', 'ccHead', 'financeHead', 'admin'] },
    { key: 'aadhaar', label: 'Aadhaar', type: 'pii', piiType: 'aadhaar', roles: ['ccHead', 'financeHead', 'admin'] },
    { key: 'dob', label: 'Date of Birth', type: 'date' },
    { key: 'loyalty_tier', label: 'Loyalty Tier', type: 'badge', badgeColors: STATUS_BADGE_COLORS },
    { key: 'loyalty_points', label: 'Loyalty Points', type: 'number' },
    { key: 'registered_date', label: 'Registered On', type: 'date' },
    { key: 'segment', label: 'Segment', type: 'string' },
    { key: 'total_orders', label: 'Total Orders', type: 'number' },
    { key: 'total_spent', label: 'Total Spent', type: 'currency' },
  ],

  'customer.order': [
    { key: 'order_id', label: 'Order ID', type: 'string', sortable: true, width: '180px' },
    { key: 'article_name', label: 'Article', type: 'string', sortable: true },
    { key: 'order_date', label: 'Order Date', type: 'date', sortable: true },
    { key: 'business_line', label: 'Business Line', type: 'badge' },
    { key: 'roms_status', label: 'Status', type: 'status', badgeColors: STATUS_BADGE_COLORS, sortable: true },
    { key: 'direction', label: 'Direction', type: 'badge' },
    { key: 'total_amount', label: 'Amount', type: 'currency', sortable: true },
    { key: 'order_delivered_date', label: 'Delivered On', type: 'date' },
  ],

  'customer.ticket': [
    { key: 'ticket_id', label: 'Ticket ID', type: 'string', sortable: true, width: '130px' },
    { key: 'created_at', label: 'Created', type: 'datetime', sortable: true },
    { key: 'channel', label: 'Channel', type: 'badge' },
    { key: 'ticket_type', label: 'Type', type: 'badge' },
    { key: 'category', label: 'Category', type: 'string' },
    { key: 'priority', label: 'Priority', type: 'badge' },
    { key: 'current_status', label: 'Status', type: 'status', badgeColors: STATUS_BADGE_COLORS, sortable: true },
    { key: 'current_assignee_name', label: 'Assignee', type: 'string' },
    { key: 'sla_breached', label: 'SLA', type: 'boolean' },
  ],

  'order.detail': [
    { key: 'shipment_id', label: 'Shipment ID', type: 'string' },
    { key: 'order_id', label: 'Order ID', type: 'string' },
    { key: 'article_id', label: 'Article ID', type: 'string' },
    { key: 'article_name', label: 'Article Name', type: 'string' },
    { key: 'order_date', label: 'Order Date', type: 'date' },
    { key: 'hd_gng', label: 'HD/GNG', type: 'string' },
    { key: 'store_dc_fulfilled', label: 'Store/DC Fulfilled', type: 'string' },
    { key: 'store_no', label: 'Store No', type: 'string' },
    { key: 'sales_order_number', label: 'Sales Order Number', type: 'string' },
    { key: 'delivery_number', label: 'Delivery Number', type: 'string' },
    { key: 'roms_status', label: 'ROMS Status', type: 'status', badgeColors: STATUS_BADGE_COLORS },
    { key: 'awb_no', label: 'AWB No', type: 'string' },
    { key: 'edd', label: 'Expected Delivery Date', type: 'date' },
    { key: 'courier_partner', label: 'Courier Partner', type: 'string' },
    { key: 'order_delivered_date', label: 'Order Delivered Date', type: 'date' },
    { key: 'shipsy_grab_status', label: 'Shipsy Grab Status', type: 'string' },
    { key: 'so_shortclose_flag', label: 'SO Shortclose Flag', type: 'string' },
    { key: 'brand_type', label: 'Brand Type', type: 'string' },
    { key: 'refund_status', label: 'Refund Status', type: 'string', roles: ['nhqFinance', 'ccHead', 'financeHead', 'admin'] },
    { key: 'refund_date', label: 'Refund Date', type: 'date', roles: ['nhqFinance', 'ccHead', 'financeHead', 'admin'] },
    { key: 'utr_number', label: 'UTR Number', type: 'string', roles: ['nhqFinance', 'ccHead', 'financeHead', 'admin'] },
    { key: 'refund_amount', label: 'Refund Amount', type: 'currency', roles: ['nhqFinance', 'ccHead', 'financeHead', 'admin'] },
  ],

  'ticket.list': [
    { key: 'ticket_id', label: 'Ticket ID', type: 'string', sortable: true, width: '130px' },
    { key: 'created_at', label: 'Created', type: 'datetime', sortable: true },
    { key: 'channel', label: 'Channel', type: 'badge' },
    { key: 'vertical', label: 'Vertical', type: 'badge' },
    { key: 'ticket_type', label: 'Type', type: 'badge' },
    { key: 'category', label: 'Category', type: 'string' },
    { key: 'priority', label: 'Priority', type: 'badge' },
    { key: 'current_queue_name', label: 'Queue', type: 'string' },
    { key: 'current_status', label: 'Status', type: 'status', badgeColors: STATUS_BADGE_COLORS, sortable: true },
    { key: 'current_assignee_name', label: 'Assignee', type: 'string' },
    { key: 'customer_name', label: 'Customer', type: 'string' },
    { key: 'sla_breached', label: 'SLA', type: 'boolean' },
    { key: 'sla_due_at', label: 'SLA Due', type: 'datetime', sortable: true },
  ],

  'ticket.detail': [
    { key: 'ticket_id', label: 'Ticket ID', type: 'string' },
    { key: 'created_at', label: 'Created At', type: 'datetime' },
    { key: 'updated_at', label: 'Updated At', type: 'datetime' },
    { key: 'channel', label: 'Channel', type: 'badge' },
    { key: 'vertical', label: 'Business Line', type: 'badge' },
    { key: 'ticket_type', label: 'Ticket Type', type: 'badge' },
    { key: 'category', label: 'Category', type: 'string' },
    { key: 'subcategory', label: 'Subcategory', type: 'string' },
    { key: 'priority', label: 'Priority', type: 'badge' },
    { key: 'current_queue_name', label: 'Current Queue', type: 'string' },
    { key: 'current_status', label: 'Status', type: 'status', badgeColors: STATUS_BADGE_COLORS },
    { key: 'current_assignee_name', label: 'Assignee', type: 'string' },
    { key: 'customer_name', label: 'Customer', type: 'string' },
    { key: 'order_id', label: 'Order ID', type: 'string' },
    { key: 'sla_due_at', label: 'SLA Due At', type: 'datetime' },
    { key: 'sla_breached', label: 'SLA Breached', type: 'boolean' },
    { key: 'first_reply_at', label: 'First Reply At', type: 'datetime' },
    { key: 'resolved_at', label: 'Resolved At', type: 'datetime' },
    { key: 'description', label: 'Description', type: 'string' },
    { key: 'resolution_notes', label: 'Resolution Notes', type: 'string' },
    { key: 'csat_score', label: 'CSAT Score', type: 'number' },
  ],

  'retailer.profile': [
    { key: 'retailer_id', label: 'Retailer ID', type: 'string' },
    { key: 'name', label: 'Business Name', type: 'string', sortable: true },
    { key: 'gstin', label: 'GSTIN', type: 'pii', piiType: 'pan' },
    { key: 'pan', label: 'PAN', type: 'pii', piiType: 'pan', roles: ['nhqFinance', 'ccHead', 'financeHead', 'admin'] },
    { key: 'retailer_type', label: 'Retailer Type', type: 'badge' },
    { key: 'business_line', label: 'Business Line', type: 'badge' },
    { key: 'contact_name', label: 'Contact Name', type: 'string' },
    { key: 'contact_phone', label: 'Contact Phone', type: 'pii', piiType: 'phone' },
    { key: 'contact_email', label: 'Contact Email', type: 'pii', piiType: 'email' },
    { key: 'address', label: 'Address', type: 'pii', piiType: 'address' },
    { key: 'city', label: 'City', type: 'string' },
    { key: 'state', label: 'State', type: 'string' },
    { key: 'pincode', label: 'Pincode', type: 'string' },
    { key: 'credit_limit', label: 'Credit Limit', type: 'currency', roles: ['nhqFinance', 'ccHead', 'financeHead', 'admin'] },
    { key: 'outstanding_amount', label: 'Outstanding Amount', type: 'currency', roles: ['nhqFinance', 'ccHead', 'financeHead', 'admin'] },
    { key: 'status', label: 'Status', type: 'status', badgeColors: STATUS_BADGE_COLORS },
    { key: 'onboarding_date', label: 'Onboarding Date', type: 'date' },
  ],

  'agent.performance': [
    { key: 'agent_name', label: 'Agent Name', type: 'string', sortable: true },
    { key: 'team_lead', label: 'Team Lead', type: 'string', sortable: true },
    { key: 'tickets_handled', label: 'Handled', type: 'number', sortable: true },
    { key: 'tickets_resolved', label: 'Resolved', type: 'number', sortable: true },
    { key: 'resolution_rate_pct', label: 'Resolution %', type: 'percent', sortable: true },
    { key: 'csat_avg', label: 'CSAT Avg', type: 'number', sortable: true },
    { key: 'aht_minutes', label: 'AHT (mins)', type: 'duration', sortable: true },
    { key: 'first_reply_avg_minutes', label: 'Avg First Reply', type: 'duration', sortable: true },
  ],

  'queue.health': [
    { key: 'queue_name', label: 'Queue', type: 'string', sortable: true },
    { key: 'total_backlog', label: 'Backlog', type: 'number', sortable: true },
    { key: 'unassigned_backlog', label: 'Unassigned', type: 'number', sortable: true },
    { key: 'sla_breached_open', label: 'SLA Breached', type: 'number', sortable: true },
    { key: 'sla_at_risk_open', label: 'SLA At Risk', type: 'number', sortable: true },
    { key: 'agents_ready', label: 'Ready', type: 'number', sortable: true },
    { key: 'agents_working', label: 'Working', type: 'number', sortable: true },
    { key: 'agents_on_break', label: 'On Break', type: 'number', sortable: true },
    { key: 'oldest_ticket_age_hours', label: 'Oldest (hrs)', type: 'number', sortable: true },
    { key: 'backlog_per_ready_agent', label: 'BL/Ready Agent', type: 'number', sortable: true },
  ],
}
