import type { ModuleConfig } from '../types/config.types'

export const MODULES_CONFIG: ModuleConfig[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    path: '/dashboard',
    order: 1,
    subModules: [
      { id: 'd1', label: 'Queue Health (Live)', path: '/dashboard/queue-health' },
      { id: 'd2', label: 'Live Agent Monitor', path: '/dashboard/live-agents' },
      { id: 'd3', label: 'Queue Performance', path: '/dashboard/queue-performance' },
      { id: 'd4', label: 'Agent Performance', path: '/dashboard/agent-performance' },
      { id: 'd5', label: 'SLA Aging by Queue', path: '/dashboard/sla-aging-queue' },
      { id: 'd6', label: 'SLA Aging by Agent', path: '/dashboard/sla-aging-agent' },
      { id: 'd7', label: 'Breaks Adherence', path: '/dashboard/breaks-adherence' },
      { id: 'd8', label: 'Ticket Aging by Queue', path: '/dashboard/ticket-aging' },
      { id: 'd9', label: 'Volume Mix', path: '/dashboard/volume-mix' },
      { id: 'd10', label: 'Trends (90D)', path: '/dashboard/trends' },
      { id: 'daily', label: 'Daily Activity Report', path: '/dashboard/daily-report' },
    ],
  },
  {
    id: 'customer360',
    label: 'Customer 360',
    icon: 'Users',
    path: '/customer360',
    order: 2,
    subModules: [],
  },
  {
    id: 'retailer360',
    label: 'Retailer 360',
    icon: 'Store',
    path: '/retailer360',
    order: 3,
    subModules: [],
  },
  {
    id: 'orderTracker',
    label: 'Order Tracker',
    icon: 'Package',
    path: '/orders',
    order: 4,
    subModules: [],
  },
  {
    id: 'ticketManagement',
    label: 'Ticket Management',
    icon: 'Ticket',
    path: '/tickets',
    order: 5,
    subModules: [],
  },
  {
    id: 'emailDashboard',
    label: 'Email Dashboard',
    icon: 'Mail',
    path: '/email-dashboard',
    order: 6,
    subModules: [
      { id: 'ed1', label: 'Overview',          path: '/email-dashboard/overview' },
      { id: 'ed2', label: 'Live Queue',         path: '/email-dashboard/live-queue' },
      { id: 'ed3', label: 'Live Agents',        path: '/email-dashboard/live-agents' },
      { id: 'ed4', label: 'Queue Performance',  path: '/email-dashboard/queue-perf' },
      { id: 'ed5', label: 'Agent Performance',  path: '/email-dashboard/agent-perf' },
      { id: 'ed6', label: 'Volume & Category',  path: '/email-dashboard/volume-category' },
      { id: 'ed7', label: 'Email Flow',         path: '/email-dashboard/email-flow' },
      { id: 'ed8', label: 'Break Report',       path: '/email-dashboard/break-report' },
    ],
  },
  {
    id: 'storeLocator',
    label: 'Store Locator',
    icon: 'MapPin',
    path: '/store-locator',
    order: 6,
    subModules: [],
  },
  {
    id: 'admin',
    label: 'Admin Panel',
    icon: 'Settings',
    path: '/admin',
    order: 7,
    subModules: [],
  },
]
